name: fast_api
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.7.1
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - click=8.0.4
  - exceptiongroup=1.1.2
  - fastapi=0.100.1
  - idna=3.4
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.10.12
  - readline=8.2
  - setuptools=68.0.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - starlette=0.27.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - aiomysql==0.2.0
      - annotated-types==0.7.0
      - black==23.9.1
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.25.1
      - iniconfig==2.0.0
      - isort==5.12.0
      - mypy-extensions==1.0.0
      - mysql-connector-python==8.0.33
      - packaging==24.2
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - protobuf==3.20.3
      - psycopg2-binary==2.9.7
      - pydantic==2.10.1
      - pydantic-core==2.27.1
      - pymysql==1.1.1
      - pytest==7.4.2
      - python-dotenv==1.0.0
      - requests==2.32.3
      - sqlalchemy==2.0.36
      - sqlmodel==0.0.22
      - tomli==2.1.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - uvicorn==0.21.1
