version: '3.9'

services:
    db:
        image: postgres:12
        container_name: sever_db
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./database/storage:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: epic
